server:
  tomcat:
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    #环境 dev|prod
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.pengan.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false


#配置logback log的配置文件路径（springboot中slf4j的实现默认使用的是logback）
logging:
  config: classpath:logback.xml


tokensessionkey:
  key: USER_SESSION_KEY
  expired: 21600
uploadfile:
  mapping: upload
  path: C:/o2o/upload/  #文件路径最后的 / 不能省略
